# Generated by Django 3.2.12 on 2023-12-02 10:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_deliverproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverproducts',
            name='paymentmod',
            field=models.CharField(default='COD', max_length=50),
        ),
        migrations.AddField(
            model_name='deliverproducts',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverproducts',
            name='quantity',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverproducts',
            name='Status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
